version: '3'

services:
  db:
    image: mysql:5.7
    #command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nopassword
      MYSQL_DATABASE: grouper
      MYSQL_USER: grouper_app
      MYSQL_PASSWORD: nopassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/:ro

  app:
    depends_on:
      - db
    image: grouper/app:1.0.0
    command: bash -c "cd /go/src/github.com/athom/grouper/cmd/grouper; go build; go install; /go/bin/grouper /go/src/github.com/athom/grouper/deploy/config.json"
    environment:
      GIN_MODE: release
    ports:
      - "7200:7200"
    volumes:
      - ../../../../../src:/go/src
